### PR TITLE
Improved translated string getter for multiple values

### PR DESCRIPTION
**Pull request by winniepukki**

### CODE REVIEW

**Comment by winniepukki** [comment]
Referencing the [corresponding issue](https://github.com/scandipwa/scandipwa/issues/2067)

**Comment by yeegor** [comment]
I do not think this is valid...
Current solution:
image

Your solution:
image

**Comment by winniepukki** [comment]
Please compare current solution with this improvement again

**Comment by yeegor** [comment]
Hah, it's the contrary! Lol sleepy me

**Pull request merged**
